# PyTorch

In [1]:
import torch
import torch.nn as nn

## Basic Operations
https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

In [2]:
x = torch.Tensor(2,3)
print(x) #float tensor of zeros size=(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
#OPERATION SYNTAX
y = torch.rand(2,3)
z1 = x + y  #operator overloading
z2 = torch.add(x,y) #same as above
print(z1==z2)

tensor([[True, True, True],
        [True, True, True]])


In [19]:
#INPLACE OPERATIONS
#followed by "_"
x.add_(y)  #add y to x in-place
print(x)

tensor([[6.9271e-01, 7.0030e-01, 3.4164e+21],
        [2.7881e-01, 4.7309e-01, 1.4451e-01]])


## Indexing

In [7]:
print(x[:, 0]) #all rows, first column 
print(x[0, :]) #all columns, first row

#the first position in a slice is the outtermost dimension in
# vector format (dim1, dim2, dim3) [dim1[dim2[dim3]],[dim2[dim3]]]

tensor([0., 0.])
tensor([0., 0., 0.])


In [8]:
#METADATA
print(x.size()) #size of x
print(torch.numel(x)) #num elements in x

torch.Size([2, 3])
6


In [9]:
#RESHAPING A TENSOR ~ .VIEW()
x = torch.randn(2,3)
y = x.view(6)
z = x.view(3,-1)
print(x)
print(y)
print(z)

tensor([[ 0.1091, -0.7261, -0.0272],
        [ 0.1972, -1.8981, -1.3471]])
tensor([ 0.1091, -0.7261, -0.0272,  0.1972, -1.8981, -1.3471])
tensor([[ 0.1091, -0.7261],
        [-0.0272,  0.1972],
        [-1.8981, -1.3471]])


## Identity Matrix Fill Tensor w/ 0, 1

In [10]:
#IDENTITY MATRIX ~ torch.eye()
identity = torch.eye(3) #3x3 identity
print(identity)

#Vector of ones ~ torch.ones()
v = torch.ones(2,1,2,1)
print(v)
v = torch.ones_like(identity) #ones w same shape as identity
print(v)

#FILL ~ .fill_()
v[1].fill_(2) #FILL Second row with 2's
v[2].fill_(3)
print(v)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


## Initialize Tensors with Range

In [11]:
# torch.ARANGE()  Returns type long
v = torch.arange(0,5)
print(v)
v = torch.arange(0,5,2) #range(0,5,step=2)
print(v)

# torch.LINSPACE()   #returns type float
v = torch.linspace(0,10,12) #Split [0,10] in 12 linear steps
print(v)
v = torch.logspace(0,10,12) #split [0,10] in 12 log steps
print(v)

tensor([0, 1, 2, 3, 4])
tensor([0, 2, 4])
tensor([ 0.0000,  0.9091,  1.8182,  2.7273,  3.6364,  4.5455,  5.4545,  6.3636,
         7.2727,  8.1818,  9.0909, 10.0000])
tensor([1.0000e+00, 8.1113e+00, 6.5793e+01, 5.3367e+02, 4.3288e+03, 3.5112e+04,
        2.8480e+05, 2.3101e+06, 1.8738e+07, 1.5199e+08, 1.2328e+09, 1.0000e+10])


## Indexing, Slicing, Joining, Mutating



### Recombining Data
- CONCAT join data on an existing dim
- STACK join data on a new dim

In [12]:
v = torch.arange(0,9).view(3, 3)
print(v, '\n')

#CONCATENATE, STACK
"""
Both cat and stack require tensors of the same shape.
CAT - combines on a given EXISTING dimension
STACK - combines tensors on a new dimension
"""
#torch.CAT()
cat = torch.cat((v,v,v), dim=0)
print(cat, cat.shape,'\n')
cat = torch.cat((v,v,v), dim=1)
print(cat, cat.shape, '\n')

#torch.STACK()
stack = torch.stack((v, v))
print(stack, stack.shape)#stacks array on a new dimension

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) torch.Size([9, 3]) 

tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8, 6, 7, 8]]) torch.Size([3, 9]) 

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]) torch.Size([2, 3, 3])


In [13]:
#GATHER: Reorganize Data Elements
print(v,'\n')
out = torch.gather(v, 1, torch.LongTensor([[0,1,2],[2,1,0],[2,1,2]]))
print(out)
# torch.gather(input, dim, index, out=None)
# out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
# out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
# out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 

tensor([[0, 1, 2],
        [5, 4, 3],
        [8, 7, 8]])


### Seperate a Tensor into multiple.
- CHUNK a tensor into N distinct Tensors
- SPLIT a tensor every N rows/columns

In [14]:
#CHUNK A TENSOR, -> Choost the NUMBER OF OUTPUT TENSORS
"""chunk(input, chunks, dim=0)
Splits a tensor into a specific number of chunks.
Last chunk will be smaller if the tensor size along the given 
dimension`dim` is not divisible by `chunks`."""

#Split the tensor into N chunks on dimension 'dim'

#Chunk by rows (2D) ~torch.CHUNK()
r = torch.chunk(v, 2, dim=0) #2 Chunks, shape (2,3), (1,3)
print(r, '\n')

#Recombine
print( torch.cat((r[0],r[1]), dim = 0) ,'\n')

#Chunk by columns (2D)
r = torch.chunk(v, 2, 1) # 2 tensors, shape (3,2), (3,1)
print(r, '\n')

#Recombine
print( torch.cat((r[0],r[1]), dim = 1) )

(tensor([[0, 1, 2],
        [3, 4, 5]]), tensor([[6, 7, 8]])) 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 

(tensor([[0, 1],
        [3, 4],
        [6, 7]]), tensor([[2],
        [5],
        [8]])) 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [15]:
# SPLIT A TENSOR -> choose the SIZE OF OUTPUT TENSORS
"""
torch.split(tensor, split_size_or_sections, dim=0)
"""
#Split the tensor every N rows/columns on dimension 'dim'
v = torch.arange(0,25).view(5,5)
print(v,'\n')


#split every 1 rows 
r = torch.split(v, 1, 0)
print(r,'\n')

#Split every 2 rows
r = torch.split(v, 2, 0)
print(r,'\n')

#Split every 2 columns
r = torch.split(v, 2, 1)
print(r)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]) 

(tensor([[0, 1, 2, 3, 4]]), tensor([[5, 6, 7, 8, 9]]), tensor([[10, 11, 12, 13, 14]]), tensor([[15, 16, 17, 18, 19]]), tensor([[20, 21, 22, 23, 24]])) 

(tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]), tensor([[20, 21, 22, 23, 24]])) 

(tensor([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]), tensor([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23]]), tensor([[ 4],
        [ 9],
        [14],
        [19],
        [24]]))


## Index Select, Mask Select

In [93]:
#INDEX SELECT
"""
index_select(input, dim, index, out=None) -> Tensor

Returns a new tensor which indexes the :attr:`input` tensor 
along dimension :attr:`dim` using the entries in :attr:`index` 
which is a `LongTensor`.

"""

#torch.INDEX_SELECT(tensor, dim, index)
indx = torch.LongTensor([0,2])
r = torch.index_select(v, 1, indx) #Same as v[:,[0,2]] (columns)

print(v[:,[0,2]], '\n')
print(r,'\n')

r = torch.index_select(v, 0, indx)
print(r) # same as v[[0,2],:]   (rows)

tensor([[ 0,  2],
        [ 5,  7],
        [10, 12],
        [15, 17],
        [20, 22]]) 

tensor([[ 0,  2],
        [ 5,  7],
        [10, 12],
        [15, 17],
        [20, 22]]) 

tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]])


In [99]:
#MASK SELECT
"""
masked_select(input, mask, out=None) -> Tensor

Returns a new 1-D tensor which indexes the :attr:`input` tensor 
according to the boolean mask :attr:`mask` which is a `BoolTensor`.
"""

mask = v.ge(9) #same as v>=3
print(mask, '\n')
r = torch.masked_select(v, mask) # same as v[mask]


print(r)

tensor([[False, False, False, False, False],
        [False, False, False, False,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]) 

tensor([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])


## SQUEEZE ~ REMOVE UNNECESSARY DIMENSIONS


In [20]:
t = torch.ones(2,1,1,2)
print(t, t.shape,'\n')

"""
squeeze(input, dim=None, out=None) -> Tensor

Returns a tensor with all the dimensions of `input` 
of size `1` removed.
"""

t = torch.squeeze(t)
print(t, t.shape)

tensor([[[[1., 1.]]],


        [[[1., 1.]]]]) torch.Size([2, 1, 1, 2]) 

tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])


## UNSQUEEZE ~ X dimension tensor to X+1 dimension

In [26]:
#ADD EXTRA DIMENSIONS
t = torch.Tensor([1,2,3])
print(t, t.shape)

"""
unsqueeze(input, dim, out=None) -> Tensor

Returns a new tensor with a dimension of size one inserted at the
specified position.
"""

#current dim is (3)
#can insert a dimension at 0 -> (1,3)
r = torch.unsqueeze(t,0)
print(r, r.shape)

#or insert dimension at 1 -> (3,1)
r = torch.unsqueeze(t,1)
print(r, r.shape)



tensor([1., 2., 3.]) torch.Size([3])
tensor([[1., 2., 3.]]) torch.Size([1, 3])
tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])


# TRANSPOSE

In [28]:
print(v,'\n')

"""
transpose(input, dim0, dim1) -> Tensor

Returns a tensor that is a transposed version of :attr:`input`.
The given dimensions :attr:`dim0` and :attr:`dim1` are swapped.

The resulting :attr:`out` tensor shares it's underlying storage with the
:attr:`input` tensor, so changing the content of one would change the content
of the other.
"""

print(torch.transpose(v, 0, 1))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]) 

tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])


## UNBIND ~ Remove a Tensor Dimension

In [46]:
"""
unbind(input, dim=0) -> seq

Removes a tensor dimension.

Returns a tuple of all slices along a given dimension, 
already without it.
"""

r = torch.unbind(v,1)
r

(tensor([ 0,  5, 10, 15, 20]),
 tensor([ 1,  6, 11, 16, 21]),
 tensor([ 2,  7, 12, 17, 22]),
 tensor([ 3,  8, 13, 18, 23]),
 tensor([ 4,  9, 14, 19, 24]))

In [47]:
print(r[0].shape)
#READD THE DIMENSION
r = [torch.unsqueeze(i,0) for i in r]
print(r[0].shape)

#RECOMBINE ONF NEW DIMENSION
torch.cat(r,dim=0)

torch.Size([5])
torch.Size([1, 5])


tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])

# Distribution

## Fill a Tensor with randomized values.

In [68]:
#SET SEED
torch.manual_seed(1)

#Fill w/ UNIFORM continuous random variables (range 0,1)
r = torch.Tensor(3,3).uniform_(0, to=1) #torch.rand
print("UNIFORM: ",r,'\n')

#Fill w/ UNIFORM discrete rv
r= torch.Tensor(3,3).random_(0,10)
print("UNIFORM (discrete): ",r,'\n')

## Size: 2x2. Bernoulli with probability p stored in elements of r
r = torch.Tensor(3,3).bernoulli_(p=0.5)
print("BERNOULLI: ",r,'\n')

#NORMAL   torch.randn()
r = torch.Tensor(3,3).normal_(mean=0, std=1)
print("NORMAL: ",r,'\n')

#EXPONENTIAL
r = torch.Tensor(3,3).exponential_(lambd=1)
print("EXPONENTIAL: ",r,'\n')

UNIFORM:  tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]]) 

UNIFORM (discrete):  tensor([[2., 8., 9.],
        [6., 3., 3.],
        [0., 2., 1.]]) 

BERNOULLI:  tensor([[1., 1., 1.],
        [0., 1., 1.],
        [1., 1., 0.]]) 

NORMAL:  tensor([[ 0.0436,  1.3240, -0.1005],
        [ 0.6443,  0.5244,  1.0157],
        [ 0.2571, -0.9013,  0.8138]]) 

EXPONENTIAL:  tensor([[0.1522, 0.3676, 0.0485],
        [0.0577, 0.1941, 0.8243],
        [0.0975, 0.0281, 0.2311]]) 



# Pointwise Operations

In [81]:
r = torch.Tensor(5,5).normal_(0,1)
print(r,'\n')

#ABS VALUES
torch.abs(r)

#ADD SCALAR
torch.add(r, 10)

#CLAMP TO RANGE [min, max] #will round up
print("CLAMP: ",torch.clamp(r,-0.5,0.5),'\n')

#RECIPROCAL
torch.reciprocal(r)

#EXPONENTIAL
torch.exp(r)

#NATURAL LOG
torch.log(r)

#Take power of each element in tensor
torch.pow(r, 2)

#SIGMOID
torch.sigmoid(r)

#SQRT
torch.sqrt(r)

#TRUNCATE TO INTEGER
torch.trunc(r)

tensor([[-0.3969,  0.4049,  0.3415, -0.3499, -0.2344],
        [-0.5452,  0.2751, -1.1834,  1.7359, -0.5309],
        [ 0.9356, -0.8873,  0.5298,  0.2684,  0.3501],
        [-0.2723,  1.0666,  0.7679, -0.3329, -0.9173],
        [ 0.8372,  1.4950, -0.8303, -1.9901, -0.8779]]) 

CLAMP:  tensor([[-0.3969,  0.4049,  0.3415, -0.3499, -0.2344],
        [-0.5000,  0.2751, -0.5000,  0.5000, -0.5000],
        [ 0.5000, -0.5000,  0.5000,  0.2684,  0.3501],
        [-0.2723,  0.5000,  0.5000, -0.3329, -0.5000],
        [ 0.5000,  0.5000, -0.5000, -0.5000, -0.5000]]) 



tensor([[-0.,  0.,  0., -0., -0.],
        [-0.,  0., -1.,  1., -0.],
        [ 0., -0.,  0.,  0.,  0.],
        [-0.,  1.,  0., -0., -0.],
        [ 0.,  1., -0., -1., -0.]])

# Reduction Operations

In [105]:
v = torch.linspace(0,9,9).view(3,3)
print(v,'\n')

#Sum along dimension
print("SUM", torch.sum(v,1,keepdim=True),'\n') #sum rows

#Adds at each element in tensor.
print("CUMSUM", torch.cumsum(v, 1),'\n')

#product
print("PRODUCT", torch.prod(v, 1, keepdim=True),'\n')

#mean of rows
print("MEAN", torch.mean(v,1,keepdim=True),'\n')

#variance
print("VARIANCE", torch.var(v,1,keepdim=True),'\n')

tensor([[0.0000, 1.1250, 2.2500],
        [3.3750, 4.5000, 5.6250],
        [6.7500, 7.8750, 9.0000]]) 

SUM tensor([[ 3.3750],
        [13.5000],
        [23.6250]]) 

CUMSUM tensor([[ 0.0000,  1.1250,  3.3750],
        [ 3.3750,  7.8750, 13.5000],
        [ 6.7500, 14.6250, 23.6250]]) 

PRODUCT tensor([[  0.0000],
        [ 85.4297],
        [478.4062]]) 

MEAN tensor([[1.1250],
        [4.5000],
        [7.8750]]) 

VARIANCE tensor([[1.2656],
        [1.2656],
        [1.2656]]) 



# Matrix - Vector Mutiplication

### Multiplying two vectors

In [139]:
#Dot product of 2 tensors
"""
dot(input, tensor) -> Tensor

Computes the dot product (inner product) of two tensors. 1D
"""
r = torch.dot(torch.Tensor([4,2]),torch.Tensor([3,1]))
print(r)

tensor(14.)


### Multiplying a Matrix and a Vector

In [ ]:
## Matrix - Vector Products
mat = torch.arange(8).view(2,4)
vec = torch.arange(4)
print(mat, mat.shape, '\n')
print(vec, vec.shape,'\n')

r = torch.mv(mat, vec) #similar to dot product
print(r,'\n')

In [ ]:
mat = torch.arange(8).view(2,4)
vec = torch.arange(4)
print(mat, mat.shape, '\n')
print(vec, vec.shape,'\n')

r = torch.mvadd(mat, vec) #similar to dot product
print(r,'\n')

In [136]:
vec = torch.unsqueeze(vec,1)
print(mat, mat.shape, '\n')
print(vec, vec.shape,'\n')

r = torch.mm(mat, vec) #similar to dot product
print(r,r.shape,'\n')

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]]) torch.Size([2, 4]) 

tensor([[0],
        [1],
        [2],
        [3]]) torch.Size([4, 1]) 

tensor([[14],
        [38]]) torch.Size([2, 1]) 

